
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOG_OUT = 'LOG_OUT';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_ALL_SIZES = 'GET_ALL_SIZES';
export const GET_ALL_COLORS = 'GET_ALL_COLORS';
export const GET_ALL_BRANDS = 'GET_ALL_BRANDS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const UPDATE_PROFILE_ERRORS = 'UPDATE_PROFILE_ERRORS';